framework:
    notifier:
        chatter_transports:
            slack: '%env(SLACK_DSN)%'
        texter_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['chat/slack', 'email']
            high: ['chat/slack', 'email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
